use crate::output;
use crate::DocsCommand;
use crate::OutputFormat;
use lode_core::{build_catalog, default_config};

pub(crate) fn docs_command(command: DocsCommand) -> lode_core::Result<()> {
    match command {
        DocsCommand::Generate { out, force, output } => docs_generate(out, force, output),
        DocsCommand::Check { dir, output } => docs_check(dir, output),
    }
}

fn docs_generate(
    out: Option<camino::Utf8PathBuf>,
    _force: bool,
    output: OutputFormat,
) -> lode_core::Result<()> {
    let config = default_config();
    let catalog = build_catalog(&config);
    let out_dir = out.unwrap_or_else(|| camino::Utf8PathBuf::from("docs"));
    let root = lode_core::ValidatedRoot::new(&out_dir)?;

    let mut generated = 0usize;

    // Profile catalog
    let mut profile_docs = String::from("# Profile Catalog\n\n");
    for entry in &catalog.entries {
        if entry.kind != "profile" {
            continue;
        }
        profile_docs.push_str(&format!("## {}\n\n", entry.id));
        profile_docs.push_str(&format!("**Summary:** {}\n\n", entry.summary));
        profile_docs.push_str(&format!("**Status:** {}  \n", entry.status));
        profile_docs.push_str(&format!("**Maturity:** {}  \n", entry.maturity));
        if let Some(qs) = entry.quality_score {
            profile_docs.push_str(&format!("**Quality:** {}/100  \n", qs));
        }
        if !entry.languages.is_empty() && entry.languages != ["*"] {
            profile_docs.push_str(&format!(
                "**Languages:** {}  \n",
                entry.languages.join(", ")
            ));
        }
        profile_docs.push('\n');
    }
    root.write_atomic("profiles.md", &profile_docs)?;
    generated += 1;

    // Recipe catalog
    let mut recipe_docs = String::from("# Recipe Catalog\n\n");
    for entry in &catalog.entries {
        if entry.kind != "recipe" {
            continue;
        }
        recipe_docs.push_str(&format!("## {}\n\n", entry.id));
        recipe_docs.push_str(&format!("**Summary:** {}\n\n", entry.summary));
        recipe_docs.push_str(&format!("**Status:** {}  \n", entry.status));
        if let Some(qs) = entry.quality_score {
            recipe_docs.push_str(&format!("**Quality:** {}/100  \n", qs));
        }
        if !entry.requires.is_empty() {
            recipe_docs.push_str(&format!("**Requires:** {}  \n", entry.requires.join(", ")));
        }
        if !entry.recommends.is_empty() {
            recipe_docs.push_str(&format!(
                "**Recommends:** {}  \n",
                entry.recommends.join(", ")
            ));
        }
        recipe_docs.push('\n');
    }
    root.write_atomic("recipes.md", &recipe_docs)?;
    generated += 1;

    // Command catalog
    let mut cmd_docs = String::from("# Command Catalog\n\n");
    for entry in &catalog.entries {
        if entry.kind != "command" {
            continue;
        }
        cmd_docs.push_str(&format!(
            "- `{}` — {} ({})  \n",
            entry.id, entry.summary, entry.status
        ));
    }
    root.write_atomic("commands.md", &cmd_docs)?;
    generated += 1;

    // Template catalog
    let mut tmpl_docs = String::from("# Template Catalog\n\n");
    for entry in &catalog.entries {
        if entry.kind != "template" {
            continue;
        }
        tmpl_docs.push_str(&format!(
            "- `{}` — {} ({})  \n",
            entry.id, entry.summary, entry.status
        ));
    }
    root.write_atomic("templates.md", &tmpl_docs)?;
    generated += 1;

    // Readme index
    let mut index = format!("# LODE Asset Documentation\n\n");
    index.push_str(&format!(
        "Generated from {} catalog entries.\n\n",
        catalog.entries.len()
    ));
    index.push_str("## Sections\n\n");
    index.push_str("- [Profiles](profiles.md)\n");
    index.push_str("- [Recipes](recipes.md)\n");
    index.push_str("- [Commands](commands.md)\n");
    index.push_str("- [Templates](templates.md)\n");
    index.push_str("\n---\n\n");
    index.push_str(&format!("*Auto-generated by `lode docs generate`*\n"));
    root.write_atomic("README.md", &index)?;
    generated += 1;

    if output.should_use_json() {
        println!(
            "{}",
            serde_json::json!({
                "generated": generated,
                "output_dir": out_dir.to_string(),
                "files": ["profiles.md", "recipes.md", "commands.md", "templates.md", "README.md"],
            })
        );
    } else {
        println!(
            "{}  Generated {} documentation files in {}",
            output::green("✔"),
            generated,
            out_dir,
        );
        for name in &[
            "profiles.md",
            "recipes.md",
            "commands.md",
            "templates.md",
            "README.md",
        ] {
            println!("  {}  {}", output::dim("·"), name);
        }
    }
    Ok(())
}

fn docs_check(dir: Option<camino::Utf8PathBuf>, output: OutputFormat) -> lode_core::Result<()> {
    let config = default_config();
    let catalog = build_catalog(&config);
    let docs_dir = dir.unwrap_or_else(|| camino::Utf8PathBuf::from("docs"));

    let expected_files = [
        "profiles.md",
        "recipes.md",
        "commands.md",
        "templates.md",
        "README.md",
    ];

    let mut missing = Vec::new();
    let mut present = 0usize;

    for name in &expected_files {
        let path = docs_dir.join(name);
        if path.exists() {
            present += 1;
        } else {
            missing.push(*name);
        }
    }

    let total_kinds: Vec<&str> = ["profile", "recipe", "command", "template"]
        .iter()
        .filter(|k| catalog.entries.iter().any(|e| e.kind == **k))
        .copied()
        .collect();

    if output.should_use_json() {
        println!(
            "{}",
            serde_json::json!({
                "present": present,
                "missing": missing,
                "expected": expected_files.len(),
                "asset_kinds": total_kinds,
            })
        );
    } else {
        if missing.is_empty() {
            println!(
                "{}  Documentation complete: {}/{} files present",
                output::green("✔"),
                present,
                expected_files.len()
            );
        } else {
            println!(
                "{}  Documentation incomplete: {}/{} files present",
                output::yellow("⚠"),
                present,
                expected_files.len()
            );
            for name in &missing {
                println!("  {}  {} missing", output::red("✘"), name);
            }
            println!("\n  Run `lode docs generate` to create missing docs.");
        }
    }
    Ok(())
}
