#![deny(unsafe_code)]

use std::fs;

use lode_core::{global_asset_dir, recipe_names, LodeError, ValidatedRoot};

use crate::{LibraryCommand, RecipeCommand};

pub(crate) fn recipe_command(command: RecipeCommand) -> lode_core::Result<()> {
    match command {
        RecipeCommand::List => {
            for recipe in recipe_names() {
                println!("{recipe}");
            }
        }
        RecipeCommand::Show { name, output } => {
            if output.should_use_json() {
                let recipes_dir = global_asset_dir("recipes")?;
                let path = recipes_dir.join(format!("{name}.toml"));
                let content = std::fs::read_to_string(&path)
                    .map_err(|e| LodeError::Message(format!("recipe not found: {name}: {e}")))?;
                let value: serde_json::Value = toml::from_str(&content)
                    .map_err(|e| LodeError::Message(format!("failed to parse recipe: {e}")))?;
                println!(
                    "{}",
                    serde_json::to_string_pretty(&value)
                        .map_err(|e| LodeError::Message(e.to_string()))?
                );
                return Ok(());
            }
            crate::cmd::template::library_command(
                "recipes",
                LibraryCommand::Show { name, raw: true },
                recipe_names(),
            )?;
        }
        RecipeCommand::Apply { name, dry_run } => apply_recipe(&name, dry_run)?,
        RecipeCommand::Compose { names } => {
            if names.is_empty() {
                return Err(LodeError::Message(
                    "recipe compose requires at least one recipe".to_string(),
                ));
            }
            for name in names {
                apply_recipe(&name, false)?;
            }
        }
        RecipeCommand::New { name } => new_recipe(&name)?,
    }
    Ok(())
}

fn new_recipe(name: &str) -> lode_core::Result<()> {
    let asset_dir = global_asset_dir("recipes")?;
    let root = ValidatedRoot::new(&asset_dir)?;
    let relative = format!("{name}.toml");
    let path = asset_dir.join(&relative);
    if path.exists() {
        return Err(LodeError::Message(format!("recipe already exists: {name}")));
    }
    let contents = format!(
        "name = \"{name}\"\ndescription = \"Custom {name} recipe\"\n\n[[files]]\ntemplate = \"docs/index.md\"\ndest = \"docs/{name}.md\"\n"
    );
    root.write_atomic(relative, contents)?;
    println!("created recipe {name}");
    Ok(())
}

fn apply_recipe(name: &str, dry_run: bool) -> lode_core::Result<()> {
    let recipe_path = global_asset_dir("recipes")?.join(format!("{name}.toml"));
    let raw = fs::read_to_string(&recipe_path).map_err(|source| LodeError::Io {
        path: recipe_path.as_str().into(),
        source,
    })?;
    let value: toml::Value =
        toml::from_str(&raw).map_err(|error| LodeError::Message(error.to_string()))?;
    let Some(files) = value.get("files").and_then(toml::Value::as_array) else {
        println!("recipe {name} has no files");
        return Ok(());
    };
    let project_dir = crate::current_dir()?;
    let root = ValidatedRoot::new(&project_dir)?;

    for file in files {
        let template = file
            .get("template")
            .and_then(toml::Value::as_str)
            .ok_or_else(|| LodeError::Message(format!("recipe {name} file missing template")))?;
        let dest = file
            .get("dest")
            .and_then(toml::Value::as_str)
            .ok_or_else(|| LodeError::Message(format!("recipe {name} file missing dest")))?;
        if dry_run {
            println!("would write {dest} from {template}");
            continue;
        }
        let relative = crate::safe_relative_path(dest)?;
        let destination = project_dir.join(&relative);
        if let Some(parent) = relative.parent() {
            root.create_dir_all(parent)?;
        }
        let contents = read_template_asset(template)
            .unwrap_or_else(|_| format!("# {dest}\n\nGenerated by recipe {name}.\n"));
        root.write_atomic(relative, contents)?;
        println!("wrote {destination}");
    }
    Ok(())
}

fn read_template_asset(path: &str) -> lode_core::Result<String> {
    let template_path = global_asset_dir("templates")?.join(path);
    fs::read_to_string(&template_path).map_err(|source| LodeError::Io {
        path: template_path.as_str().into(),
        source,
    })
}
